language: node_js
node_js:
  - '0.8'
  - '0.10'
branches:
  only:
    - master
before_install:
  - npm install -g grunt-cli
script:
  - grunt test --env=ci
env:
  global:
    - secure: NuiakrPV0H1z6iDAYPZimDqBGT4JRcevpv4a4ZHUyknv1BDdkbm58S84FucOkCibMARmZ4SPwhanCpMcA7lzhdeOZE2d9NqRCA92vK4IwIczK7Kl60J/mQNlL3giV91iQW06yHdU8wipgwnYwvfmfDgfIy6xH8waw0lRdlD2r8U=
    - secure: hP8i4BBa7IT/qvVqGcAk+3B868+YjPWV4Ksqb72FE60FjM02yTm8xkHZb/gr6cWyNo3EzR3unKi2fg1xciSeEdkc4qsUA8EMdJEaJDRgKJmrc01aAats/JXGrooHHjzdTYmY+LUSMipi0GeoMIZ+eJgg8qprsFat1LQeUhy+t90=
