language: node_js
node_js:
  - 0.8
branches:
  only:
  - master
before_install:
  - npm install -g grunt@0.3.17
before_script:
  - grunt build:sdk
env:
  global:
  - secure: ! 'MbsUPTGm6kuDyoExK12UqNwVK1NZMbO+gggblNL15ZYzT7uDExO1WnXifxn5

      TIKktCb9EHIeYL7sBu72YEU93Htkl9FpIX/yLbL9/gORSOwcdCPFXMgk+Vrw

      YfhQQkU0V0BmtkH+YeAPNtqo1CfzMHJhhsWIupbGzKeAhrSipBc='
  - secure: ! 'QFRM55n14yW+DLiq7t8P/tS5nkrQCrvgEgULtSSjfnBLyW7Qs2BD3C1ju0iL

      K4vYmdQ2PNPOXAg4AuoC4uqUMS4h0a+EBlN8j+2XlH7+3/L1H4cvXbypuzae

      IfwxuqJ5Mg0EGJGeKfi7AbGnHeO1h8Gilm8ic4nvtmyb6Yfngx4='
